server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: master-data-management

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    generate-ddl: false
    open-in-view: false

  datasource:
    url: jdbc:mysql://master-data-management.c3qu1hehhhiv.us-east-1.rds.amazonaws.com:3306/master_data
    username: masterdatauser
    password: masterdatapassword
    driverClassName: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      idleTimeout: 60000
      minimumIdle: 2
      maximumPoolSize: 20
      connectionTimeout: 30000
      connectionTestQuery: SELECT 1
      poolName: master_data_management_pool

# https://www.baeldung.com/spring-boot-actuators
management:
  endpoints:
    web:
      exposure:
        include: health, metric, info, prometheus
  endpoint:
    health:
      show-details: always

microservice-framework:
  core:
    validate-generic-headers: false # Change to true later once x-request-id is ready from client side
    request-response-log:
      log-payload: true
      log-req-headers: true
      max-payload-size: 3000

#logging:
#  config: /logback/logback-spring.xml