-- Source: https://www.html-code-generator.com/mysql/country-name-table

CREATE TABLE IF NOT EXISTS `COUNTRY` (
    `COUNTRY_ID` int(11) NOT NULL AUTO_INCREMENT,
    `COUNTRY_CODE` char(2) NOT NULL,
    `COUNTRY_CODE_ISO3` char(3) NOT NULL,
    `COUNTRY_NAME` varchar(100) NOT NULL,
    `CAPITAL_NAME` varchar(80) NOT NULL,
    `PHONE_CODE` int(5) NOT NULL,
    `CURRENCY_SYMBOL` varchar(10) NOT NULL,
    `CURRENCY` varchar(3)  NOT NULL,
    `CONTINENT_CODE` varchar(2) NOT NULL,
    `CONTINENT_NAME` varchar(30) NOT NULL,
    PRIMARY KEY (`COUNTRY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=253 DEFAULT CHARSET=utf8;

-- https://www.html-code-generator.com/mysql/country-name-table

INSERT INTO `COUNTRY` (`COUNTRY_ID`, `COUNTRY_CODE`, `COUNTRY_CODE_ISO3`, `COUNTRY_NAME`, `CAPITAL_NAME`, `PHONE_CODE`, `CURRENCY_SYMBOL`, `CURRENCY`, `CONTINENT_CODE`, `CONTINENT_NAME`) VALUES
(1, 'AF', 'AFG', 'Afghanistan', 'Kabul', 93, '؋', 'AFN', 'AS', 'Asia'),
(2, 'AX', 'ALA', 'Aland Islands', 'Mariehamn', 358, '€', 'EUR', 'EU', 'Europe'),
(3, 'AL', 'ALB', 'Albania', 'Tirana', 355, 'Lek', 'ALL', 'EU', 'Europe'),
(4, 'DZ', 'DZA', 'Algeria', 'Algiers', 213, 'دج', 'DZD', 'AF', 'Africa'),
(5, 'AS', 'ASM', 'American Samoa', 'Pago Pago', 1684, '$', 'USD', 'OC', 'Oceania'),
(6, 'AD', 'AND', 'Andorra', 'Andorra la Vella', 376, '€', 'EUR', 'EU', 'Europe'),
(7, 'AO', 'AGO', 'Angola', 'Luanda', 244, 'Kz', 'AOA', 'AF', 'Africa'),
(8, 'AI', 'AIA', 'Anguilla', 'The Valley', 1264, '$', 'XCD', 'NA', 'North America'),
(9, 'AQ', 'ATA', 'Antarctica', 'Antarctica', 672, '$', 'AAD', 'AN', 'Antarctica'),
(10, 'AG', 'ATG', 'Antigua and Barbuda', 'St. John\'s', 1268, '$', 'XCD', 'NA', 'North America'),
(11, 'AR', 'ARG', 'Argentina', 'Buenos Aires', 54, '$', 'ARS', 'SA', 'South America'),
(12, 'AM', 'ARM', 'Armenia', 'Yerevan', 374, '֏', 'AMD', 'AS', 'Asia'),
(13, 'AW', 'ABW', 'Aruba', 'Oranjestad', 297, 'ƒ', 'AWG', 'NA', 'North America'),
(14, 'AU', 'AUS', 'Australia', 'Canberra', 61, '$', 'AUD', 'OC', 'Oceania'),
(15, 'AT', 'AUT', 'Austria', 'Vienna', 43, '€', 'EUR', 'EU', 'Europe'),
(16, 'AZ', 'AZE', 'Azerbaijan', 'Baku', 994, 'm', 'AZN', 'AS', 'Asia'),
(17, 'BS', 'BHS', 'Bahamas', 'Nassau', 1242, 'B$', 'BSD', 'NA', 'North America'),
(18, 'BH', 'BHR', 'Bahrain', 'Manama', 973, '.د.ب', 'BHD', 'AS', 'Asia'),
(19, 'BD', 'BGD', 'Bangladesh', 'Dhaka', 880, '৳', 'BDT', 'AS', 'Asia'),
(20, 'BB', 'BRB', 'Barbados', 'Bridgetown', 1246, 'Bds$', 'BBD', 'NA', 'North America'),
(21, 'BY', 'BLR', 'Belarus', 'Minsk', 375, 'Br', 'BYN', 'EU', 'Europe'),
(22, 'BE', 'BEL', 'Belgium', 'Brussels', 32, '€', 'EUR', 'EU', 'Europe'),
(23, 'BZ', 'BLZ', 'Belize', 'Belmopan', 501, '$', 'BZD', 'NA', 'North America'),
(24, 'BJ', 'BEN', 'Benin', 'Porto-Novo', 229, 'CFA', 'XOF', 'AF', 'Africa'),
(25, 'BM', 'BMU', 'Bermuda', 'Hamilton', 1441, '$', 'BMD', 'NA', 'North America'),
(26, 'BT', 'BTN', 'Bhutan', 'Thimphu', 975, 'Nu.', 'BTN', 'AS', 'Asia'),
(27, 'BO', 'BOL', 'Bolivia', 'Sucre', 591, 'Bs.', 'BOB', 'SA', 'South America'),
(28, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Kralendijk', 599, '$', 'USD', 'NA', 'North America'),
(29, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Sarajevo', 387, 'KM', 'BAM', 'EU', 'Europe'),
(30, 'BW', 'BWA', 'Botswana', 'Gaborone', 267, 'P', 'BWP', 'AF', 'Africa'),
(31, 'BV', 'BVT', 'Bouvet Island', '', 55, 'kr', 'NOK', 'AN', 'Antarctica'),
(32, 'BR', 'BRA', 'Brazil', 'Brasilia', 55, 'R$', 'BRL', 'SA', 'South America'),
(33, 'IO', 'IOT', 'British Indian Ocean Territory', 'Diego Garcia', 246, '$', 'USD', 'AS', 'Asia'),
(34, 'BN', 'BRN', 'Brunei Darussalam', 'Bandar Seri Begawan', 673, 'B$', 'BND', 'AS', 'Asia'),
(35, 'BG', 'BGR', 'Bulgaria', 'Sofia', 359, 'Лв.', 'BGN', 'EU', 'Europe'),
(36, 'BF', 'BFA', 'Burkina Faso', 'Ouagadougou', 226, 'CFA', 'XOF', 'AF', 'Africa'),
(37, 'BI', 'BDI', 'Burundi', 'Bujumbura', 257, 'FBu', 'BIF', 'AF', 'Africa'),
(38, 'KH', 'KHM', 'Cambodia', 'Phnom Penh', 855, 'KHR', 'KHR', 'AS', 'Asia'),
(39, 'CM', 'CMR', 'Cameroon', 'Yaounde', 237, 'FCFA', 'XAF', 'AF', 'Africa'),
(40, 'CA', 'CAN', 'Canada', 'Ottawa', 1, '$', 'CAD', 'NA', 'North America'),
(41, 'CV', 'CPV', 'Cape Verde', 'Praia', 238, '$', 'CVE', 'AF', 'Africa'),
(42, 'KY', 'CYM', 'Cayman Islands', 'George Town', 1345, '$', 'KYD', 'NA', 'North America'),
(43, 'CF', 'CAF', 'Central African Republic', 'Bangui', 236, 'FCFA', 'XAF', 'AF', 'Africa'),
(44, 'TD', 'TCD', 'Chad', 'N\'Djamena', 235, 'FCFA', 'XAF', 'AF', 'Africa'),
(45, 'CL', 'CHL', 'Chile', 'Santiago', 56, '$', 'CLP', 'SA', 'South America'),
(46, 'CN', 'CHN', 'China', 'Beijing', 86, '¥', 'CNY', 'AS', 'Asia'),
(47, 'CX', 'CXR', 'Christmas Island', 'Flying Fish Cove', 61, '$', 'AUD', 'AS', 'Asia'),
(48, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'West Island', 672, '$', 'AUD', 'AS', 'Asia'),
(49, 'CO', 'COL', 'Colombia', 'Bogota', 57, '$', 'COP', 'SA', 'South America'),
(50, 'KM', 'COM', 'Comoros', 'Moroni', 269, 'CF', 'KMF', 'AF', 'Africa'),
(51, 'CG', 'COG', 'Congo', 'Brazzaville', 242, 'FC', 'XAF', 'AF', 'Africa'),
(52, 'CD', 'COD', 'Congo, Democratic Republic of the Congo', 'Kinshasa', 242, 'FC', 'CDF', 'AF', 'Africa'),
(53, 'CK', 'COK', 'Cook Islands', 'Avarua', 682, '$', 'NZD', 'OC', 'Oceania'),
(54, 'CR', 'CRI', 'Costa Rica', 'San Jose', 506, '₡', 'CRC', 'NA', 'North America'),
(55, 'CI', 'CIV', 'Cote D\'Ivoire', 'Yamoussoukro', 225, 'CFA', 'XOF', 'AF', 'Africa'),
(56, 'HR', 'HRV', 'Croatia', 'Zagreb', 385, 'kn', 'HRK', 'EU', 'Europe'),
(57, 'CU', 'CUB', 'Cuba', 'Havana', 53, '$', 'CUP', 'NA', 'North America'),
(58, 'CW', 'CUW', 'Curacao', 'Willemstad', 599, 'ƒ', 'ANG', 'NA', 'North America'),
(59, 'CY', 'CYP', 'Cyprus', 'Nicosia', 357, '€', 'EUR', 'AS', 'Asia'),
(60, 'CZ', 'CZE', 'Czech Republic', 'Prague', 420, 'Kč', 'CZK', 'EU', 'Europe'),
(61, 'DK', 'DNK', 'Denmark', 'Copenhagen', 45, 'Kr.', 'DKK', 'EU', 'Europe'),
(62, 'DJ', 'DJI', 'Djibouti', 'Djibouti', 253, 'Fdj', 'DJF', 'AF', 'Africa'),
(63, 'DM', 'DMA', 'Dominica', 'Roseau', 1767, '$', 'XCD', 'NA', 'North America'),
(64, 'DO', 'DOM', 'Dominican Republic', 'Santo Domingo', 1809, '$', 'DOP', 'NA', 'North America'),
(65, 'EC', 'ECU', 'Ecuador', 'Quito', 593, '$', 'USD', 'SA', 'South America'),
(66, 'EG', 'EGY', 'Egypt', 'Cairo', 20, 'ج.م', 'EGP', 'AF', 'Africa'),
(67, 'SV', 'SLV', 'El Salvador', 'San Salvador', 503, '$', 'USD', 'NA', 'North America'),
(68, 'GQ', 'GNQ', 'Equatorial Guinea', 'Malabo', 240, 'FCFA', 'XAF', 'AF', 'Africa'),
(69, 'ER', 'ERI', 'Eritrea', 'Asmara', 291, 'Nfk', 'ERN', 'AF', 'Africa'),
(70, 'EE', 'EST', 'Estonia', 'Tallinn', 372, '€', 'EUR', 'EU', 'Europe'),
(71, 'ET', 'ETH', 'Ethiopia', 'Addis Ababa', 251, 'Nkf', 'ETB', 'AF', 'Africa'),
(72, 'FK', 'FLK', 'Falkland Islands (Malvinas)', 'Stanley', 500, '£', 'FKP', 'SA', 'South America'),
(73, 'FO', 'FRO', 'Faroe Islands', 'Torshavn', 298, 'Kr.', 'DKK', 'EU', 'Europe'),
(74, 'FJ', 'FJI', 'Fiji', 'Suva', 679, 'FJ$', 'FJD', 'OC', 'Oceania'),
(75, 'FI', 'FIN', 'Finland', 'Helsinki', 358, '€', 'EUR', 'EU', 'Europe'),
(76, 'FR', 'FRA', 'France', 'Paris', 33, '€', 'EUR', 'EU', 'Europe'),
(77, 'GF', 'GUF', 'French Guiana', 'Cayenne', 594, '€', 'EUR', 'SA', 'South America'),
(78, 'PF', 'PYF', 'French Polynesia', 'Papeete', 689, '₣', 'XPF', 'OC', 'Oceania'),
(79, 'TF', 'ATF', 'French Southern Territories', 'Port-aux-Francais', 262, '€', 'EUR', 'AN', 'Antarctica'),
(80, 'GA', 'GAB', 'Gabon', 'Libreville', 241, 'FCFA', 'XAF', 'AF', 'Africa'),
(81, 'GM', 'GMB', 'Gambia', 'Banjul', 220, 'D', 'GMD', 'AF', 'Africa'),
(82, 'GE', 'GEO', 'Georgia', 'Tbilisi', 995, 'ლ', 'GEL', 'AS', 'Asia'),
(83, 'DE', 'DEU', 'Germany', 'Berlin', 49, '€', 'EUR', 'EU', 'Europe'),
(84, 'GH', 'GHA', 'Ghana', 'Accra', 233, 'GH₵', 'GHS', 'AF', 'Africa'),
(85, 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 350, '£', 'GIP', 'EU', 'Europe'),
(86, 'GR', 'GRC', 'Greece', 'Athens', 30, '€', 'EUR', 'EU', 'Europe'),
(87, 'GL', 'GRL', 'Greenland', 'Nuuk', 299, 'Kr.', 'DKK', 'NA', 'North America'),
(88, 'GD', 'GRD', 'Grenada', 'St. George\'s', 1473, '$', 'XCD', 'NA', 'North America'),
(89, 'GP', 'GLP', 'Guadeloupe', 'Basse-Terre', 590, '€', 'EUR', 'NA', 'North America'),
(90, 'GU', 'GUM', 'Guam', 'Hagatna', 1671, '$', 'USD', 'OC', 'Oceania'),
(91, 'GT', 'GTM', 'Guatemala', 'Guatemala City', 502, 'Q', 'GTQ', 'NA', 'North America'),
(92, 'GG', 'GGY', 'Guernsey', 'St Peter Port', 44, '£', 'GBP', 'EU', 'Europe'),
(93, 'GN', 'GIN', 'Guinea', 'Conakry', 224, 'FG', 'GNF', 'AF', 'Africa'),
(94, 'GW', 'GNB', 'Guinea-Bissau', 'Bissau', 245, 'CFA', 'XOF', 'AF', 'Africa'),
(95, 'GY', 'GUY', 'Guyana', 'Georgetown', 592, '$', 'GYD', 'SA', 'South America'),
(96, 'HT', 'HTI', 'Haiti', 'Port-au-Prince', 509, 'G', 'HTG', 'NA', 'North America'),
(97, 'HM', 'HMD', 'Heard Island and Mcdonald Islands', '', 0, '$', 'AUD', 'AN', 'Antarctica'),
(98, 'VA', 'VAT', 'Holy See (Vatican City State)', 'Vatican City', 39, '€', 'EUR', 'EU', 'Europe'),
(99, 'HN', 'HND', 'Honduras', 'Tegucigalpa', 504, 'L', 'HNL', 'NA', 'North America'),
(100, 'HK', 'HKG', 'Hong Kong', 'Hong Kong', 852, '$', 'HKD', 'AS', 'Asia'),
(101, 'HU', 'HUN', 'Hungary', 'Budapest', 36, 'Ft', 'HUF', 'EU', 'Europe'),
(102, 'IS', 'ISL', 'Iceland', 'Reykjavik', 354, 'kr', 'ISK', 'EU', 'Europe'),
(103, 'IN', 'IND', 'India', 'New Delhi', 91, '₹', 'INR', 'AS', 'Asia'),
(104, 'ID', 'IDN', 'Indonesia', 'Jakarta', 62, 'Rp', 'IDR', 'AS', 'Asia'),
(105, 'IR', 'IRN', 'Iran, Islamic Republic of', 'Tehran', 98, '﷼', 'IRR', 'AS', 'Asia'),
(106, 'IQ', 'IRQ', 'Iraq', 'Baghdad', 964, 'د.ع', 'IQD', 'AS', 'Asia'),
(107, 'IE', 'IRL', 'Ireland', 'Dublin', 353, '€', 'EUR', 'EU', 'Europe'),
(108, 'IM', 'IMN', 'Isle of Man', 'Douglas, Isle of Man', 44, '£', 'GBP', 'EU', 'Europe'),
(109, 'IL', 'ISR', 'Israel', 'Jerusalem', 972, '₪', 'ILS', 'AS', 'Asia'),
(110, 'IT', 'ITA', 'Italy', 'Rome', 39, '€', 'EUR', 'EU', 'Europe'),
(111, 'JM', 'JAM', 'Jamaica', 'Kingston', 1876, 'J$', 'JMD', 'NA', 'North America'),
(112, 'JP', 'JPN', 'Japan', 'Tokyo', 81, '¥', 'JPY', 'AS', 'Asia'),
(113, 'JE', 'JEY', 'Jersey', 'Saint Helier', 44, '£', 'GBP', 'EU', 'Europe'),
(114, 'JO', 'JOR', 'Jordan', 'Amman', 962, 'ا.د', 'JOD', 'AS', 'Asia'),
(115, 'KZ', 'KAZ', 'Kazakhstan', 'Astana', 7, 'лв', 'KZT', 'AS', 'Asia'),
(116, 'KE', 'KEN', 'Kenya', 'Nairobi', 254, 'KSh', 'KES', 'AF', 'Africa'),
(117, 'KI', 'KIR', 'Kiribati', 'Tarawa', 686, '$', 'AUD', 'OC', 'Oceania'),
(118, 'KP', 'PRK', 'Korea, Democratic People\'s Republic of', 'Pyongyang', 850, '₩', 'KPW', 'AS', 'Asia'),
(119, 'KR', 'KOR', 'Korea, Republic of', 'Seoul', 82, '₩', 'KRW', 'AS', 'Asia'),
(120, 'XK', 'XKX', 'Kosovo', 'Pristina', 383, '€', 'EUR', 'EU', 'Europe'),
(121, 'KW', 'KWT', 'Kuwait', 'Kuwait City', 965, 'ك.د', 'KWD', 'AS', 'Asia'),
(122, 'KG', 'KGZ', 'Kyrgyzstan', 'Bishkek', 996, 'лв', 'KGS', 'AS', 'Asia'),
(123, 'LA', 'LAO', 'Lao People\'s Democratic Republic', 'Vientiane', 856, '₭', 'LAK', 'AS', 'Asia'),
(124, 'LV', 'LVA', 'Latvia', 'Riga', 371, '€', 'EUR', 'EU', 'Europe'),
(125, 'LB', 'LBN', 'Lebanon', 'Beirut', 961, '£', 'LBP', 'AS', 'Asia'),
(126, 'LS', 'LSO', 'Lesotho', 'Maseru', 266, 'L', 'LSL', 'AF', 'Africa'),
(127, 'LR', 'LBR', 'Liberia', 'Monrovia', 231, '$', 'LRD', 'AF', 'Africa'),
(128, 'LY', 'LBY', 'Libyan Arab Jamahiriya', 'Tripolis', 218, 'د.ل', 'LYD', 'AF', 'Africa'),
(129, 'LI', 'LIE', 'Liechtenstein', 'Vaduz', 423, 'CHf', 'CHF', 'EU', 'Europe'),
(130, 'LT', 'LTU', 'Lithuania', 'Vilnius', 370, '€', 'EUR', 'EU', 'Europe'),
(131, 'LU', 'LUX', 'Luxembourg', 'Luxembourg', 352, '€', 'EUR', 'EU', 'Europe'),
(132, 'MO', 'MAC', 'Macao', 'Macao', 853, '$', 'MOP', 'AS', 'Asia'),
(133, 'MK', 'MKD', 'Macedonia, the Former Yugoslav Republic of', 'Skopje', 389, 'ден', 'MKD', 'EU', 'Europe'),
(134, 'MG', 'MDG', 'Madagascar', 'Antananarivo', 261, 'Ar', 'MGA', 'AF', 'Africa'),
(135, 'MW', 'MWI', 'Malawi', 'Lilongwe', 265, 'MK', 'MWK', 'AF', 'Africa'),
(136, 'MY', 'MYS', 'Malaysia', 'Kuala Lumpur', 60, 'RM', 'MYR', 'AS', 'Asia'),
(137, 'MV', 'MDV', 'Maldives', 'Male', 960, 'Rf', 'MVR', 'AS', 'Asia'),
(138, 'ML', 'MLI', 'Mali', 'Bamako', 223, 'CFA', 'XOF', 'AF', 'Africa'),
(139, 'MT', 'MLT', 'Malta', 'Valletta', 356, '€', 'EUR', 'EU', 'Europe'),
(140, 'MH', 'MHL', 'Marshall Islands', 'Majuro', 692, '$', 'USD', 'OC', 'Oceania'),
(141, 'MQ', 'MTQ', 'Martinique', 'Fort-de-France', 596, '€', 'EUR', 'NA', 'North America'),
(142, 'MR', 'MRT', 'Mauritania', 'Nouakchott', 222, 'MRU', 'MRO', 'AF', 'Africa'),
(143, 'MU', 'MUS', 'Mauritius', 'Port Louis', 230, '₨', 'MUR', 'AF', 'Africa'),
(144, 'YT', 'MYT', 'Mayotte', 'Mamoudzou', 262, '€', 'EUR', 'AF', 'Africa'),
(145, 'MX', 'MEX', 'Mexico', 'Mexico City', 52, '$', 'MXN', 'NA', 'North America'),
(146, 'FM', 'FSM', 'Micronesia, Federated States of', 'Palikir', 691, '$', 'USD', 'OC', 'Oceania'),
(147, 'MD', 'MDA', 'Moldova, Republic of', 'Chisinau', 373, 'L', 'MDL', 'EU', 'Europe'),
(148, 'MC', 'MCO', 'Monaco', 'Monaco', 377, '€', 'EUR', 'EU', 'Europe'),
(149, 'MN', 'MNG', 'Mongolia', 'Ulan Bator', 976, '₮', 'MNT', 'AS', 'Asia'),
(150, 'ME', 'MNE', 'Montenegro', 'Podgorica', 382, '€', 'EUR', 'EU', 'Europe'),
(151, 'MS', 'MSR', 'Montserrat', 'Plymouth', 1664, '$', 'XCD', 'NA', 'North America'),
(152, 'MA', 'MAR', 'Morocco', 'Rabat', 212, 'DH', 'MAD', 'AF', 'Africa'),
(153, 'MZ', 'MOZ', 'Mozambique', 'Maputo', 258, 'MT', 'MZN', 'AF', 'Africa'),
(154, 'MM', 'MMR', 'Myanmar', 'Nay Pyi Taw', 95, 'K', 'MMK', 'AS', 'Asia'),
(155, 'NA', 'NAM', 'Namibia', 'Windhoek', 264, '$', 'NAD', 'AF', 'Africa'),
(156, 'NR', 'NRU', 'Nauru', 'Yaren', 674, '$', 'AUD', 'OC', 'Oceania'),
(157, 'NP', 'NPL', 'Nepal', 'Kathmandu', 977, '₨', 'NPR', 'AS', 'Asia'),
(158, 'NL', 'NLD', 'Netherlands', 'Amsterdam', 31, '€', 'EUR', 'EU', 'Europe'),
(159, 'AN', 'ANT', 'Netherlands Antilles', 'Willemstad', 599, 'NAf', 'ANG', 'NA', 'North America'),
(160, 'NC', 'NCL', 'New Caledonia', 'Noumea', 687, '₣', 'XPF', 'OC', 'Oceania'),
(161, 'NZ', 'NZL', 'New Zealand', 'Wellington', 64, '$', 'NZD', 'OC', 'Oceania'),
(162, 'NI', 'NIC', 'Nicaragua', 'Managua', 505, 'C$', 'NIO', 'NA', 'North America'),
(163, 'NE', 'NER', 'Niger', 'Niamey', 227, 'CFA', 'XOF', 'AF', 'Africa'),
(164, 'NG', 'NGA', 'Nigeria', 'Abuja', 234, '₦', 'NGN', 'AF', 'Africa'),
(165, 'NU', 'NIU', 'Niue', 'Alofi', 683, '$', 'NZD', 'OC', 'Oceania'),
(166, 'NF', 'NFK', 'Norfolk Island', 'Kingston', 672, '$', 'AUD', 'OC', 'Oceania'),
(167, 'MP', 'MNP', 'Northern Mariana Islands', 'Saipan', 1670, '$', 'USD', 'OC', 'Oceania'),
(168, 'NO', 'NOR', 'Norway', 'Oslo', 47, 'kr', 'NOK', 'EU', 'Europe'),
(169, 'OM', 'OMN', 'Oman', 'Muscat', 968, '.ع.ر', 'OMR', 'AS', 'Asia'),
(170, 'PK', 'PAK', 'Pakistan', 'Islamabad', 92, '₨', 'PKR', 'AS', 'Asia'),
(171, 'PW', 'PLW', 'Palau', 'Melekeok', 680, '$', 'USD', 'OC', 'Oceania'),
(172, 'PS', 'PSE', 'Palestinian Territory, Occupied', 'East Jerusalem', 970, '₪', 'ILS', 'AS', 'Asia'),
(173, 'PA', 'PAN', 'Panama', 'Panama City', 507, 'B/.', 'PAB', 'NA', 'North America'),
(174, 'PG', 'PNG', 'Papua New Guinea', 'Port Moresby', 675, 'K', 'PGK', 'OC', 'Oceania'),
(175, 'PY', 'PRY', 'Paraguay', 'Asuncion', 595, '₲', 'PYG', 'SA', 'South America'),
(176, 'PE', 'PER', 'Peru', 'Lima', 51, 'S/.', 'PEN', 'SA', 'South America'),
(177, 'PH', 'PHL', 'Philippines', 'Manila', 63, '₱', 'PHP', 'AS', 'Asia'),
(178, 'PN', 'PCN', 'Pitcairn', 'Adamstown', 64, '$', 'NZD', 'OC', 'Oceania'),
(179, 'PL', 'POL', 'Poland', 'Warsaw', 48, 'zł', 'PLN', 'EU', 'Europe'),
(180, 'PT', 'PRT', 'Portugal', 'Lisbon', 351, '€', 'EUR', 'EU', 'Europe'),
(181, 'PR', 'PRI', 'Puerto Rico', 'San Juan', 1787, '$', 'USD', 'NA', 'North America'),
(182, 'QA', 'QAT', 'Qatar', 'Doha', 974, 'ق.ر', 'QAR', 'AS', 'Asia'),
(183, 'RE', 'REU', 'Reunion', 'Saint-Denis', 262, '€', 'EUR', 'AF', 'Africa'),
(184, 'RO', 'ROM', 'Romania', 'Bucharest', 40, 'lei', 'RON', 'EU', 'Europe'),
(185, 'RU', 'RUS', 'Russian Federation', 'Moscow', 7, '₽', 'RUB', 'AS', 'Asia'),
(186, 'RW', 'RWA', 'Rwanda', 'Kigali', 250, 'FRw', 'RWF', 'AF', 'Africa'),
(187, 'BL', 'BLM', 'Saint Barthelemy', 'Gustavia', 590, '€', 'EUR', 'NA', 'North America'),
(188, 'SH', 'SHN', 'Saint Helena', 'Jamestown', 290, '£', 'SHP', 'AF', 'Africa'),
(189, 'KN', 'KNA', 'Saint Kitts and Nevis', 'Basseterre', 1869, '$', 'XCD', 'NA', 'North America'),
(190, 'LC', 'LCA', 'Saint Lucia', 'Castries', 1758, '$', 'XCD', 'NA', 'North America'),
(191, 'MF', 'MAF', 'Saint Martin', 'Marigot', 590, '€', 'EUR', 'NA', 'North America'),
(192, 'PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint-Pierre', 508, '€', 'EUR', 'NA', 'North America'),
(193, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Kingstown', 1784, '$', 'XCD', 'NA', 'North America'),
(194, 'WS', 'WSM', 'Samoa', 'Apia', 684, 'SAT', 'WST', 'OC', 'Oceania'),
(195, 'SM', 'SMR', 'San Marino', 'San Marino', 378, '€', 'EUR', 'EU', 'Europe'),
(196, 'ST', 'STP', 'Sao Tome and Principe', 'Sao Tome', 239, 'Db', 'STD', 'AF', 'Africa'),
(197, 'SA', 'SAU', 'Saudi Arabia', 'Riyadh', 966, '﷼', 'SAR', 'AS', 'Asia'),
(198, 'SN', 'SEN', 'Senegal', 'Dakar', 221, 'CFA', 'XOF', 'AF', 'Africa'),
(199, 'RS', 'SRB', 'Serbia', 'Belgrade', 381, 'din', 'RSD', 'EU', 'Europe'),
(200, 'CS', 'SCG', 'Serbia and Montenegro', 'Belgrade', 381, 'din', 'RSD', 'EU', 'Europe'),
(201, 'SC', 'SYC', 'Seychelles', 'Victoria', 248, 'SRe', 'SCR', 'AF', 'Africa'),
(202, 'SL', 'SLE', 'Sierra Leone', 'Freetown', 232, 'Le', 'SLL', 'AF', 'Africa'),
(203, 'SG', 'SGP', 'Singapore', 'Singapur', 65, '$', 'SGD', 'AS', 'Asia'),
(204, 'SX', 'SXM', 'Sint Maarten', 'Philipsburg', 721, 'ƒ', 'ANG', 'NA', 'North America'),
(205, 'SK', 'SVK', 'Slovakia', 'Bratislava', 421, '€', 'EUR', 'EU', 'Europe'),
(206, 'SI', 'SVN', 'Slovenia', 'Ljubljana', 386, '€', 'EUR', 'EU', 'Europe'),
(207, 'SB', 'SLB', 'Solomon Islands', 'Honiara', 677, 'Si$', 'SBD', 'OC', 'Oceania'),
(208, 'SO', 'SOM', 'Somalia', 'Mogadishu', 252, 'Sh.so.', 'SOS', 'AF', 'Africa'),
(209, 'ZA', 'ZAF', 'South Africa', 'Pretoria', 27, 'R', 'ZAR', 'AF', 'Africa'),
(210, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Grytviken', 500, '£', 'GBP', 'AN', 'Antarctica'),
(211, 'SS', 'SSD', 'South Sudan', 'Juba', 211, '£', 'SSP', 'AF', 'Africa'),
(212, 'ES', 'ESP', 'Spain', 'Madrid', 34, '€', 'EUR', 'EU', 'Europe'),
(213, 'LK', 'LKA', 'Sri Lanka', 'Colombo', 94, 'Rs', 'LKR', 'AS', 'Asia'),
(214, 'SD', 'SDN', 'Sudan', 'Khartoum', 249, '.س.ج', 'SDG', 'AF', 'Africa'),
(215, 'SR', 'SUR', 'Suriname', 'Paramaribo', 597, '$', 'SRD', 'SA', 'South America'),
(216, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Longyearbyen', 47, 'kr', 'NOK', 'EU', 'Europe'),
(217, 'SZ', 'SWZ', 'Swaziland', 'Mbabane', 268, 'E', 'SZL', 'AF', 'Africa'),
(218, 'SE', 'SWE', 'Sweden', 'Stockholm', 46, 'kr', 'SEK', 'EU', 'Europe'),
(219, 'CH', 'CHE', 'Switzerland', 'Berne', 41, 'CHf', 'CHF', 'EU', 'Europe'),
(220, 'SY', 'SYR', 'Syrian Arab Republic', 'Damascus', 963, 'LS', 'SYP', 'AS', 'Asia'),
(221, 'TW', 'TWN', 'Taiwan, Province of China', 'Taipei', 886, '$', 'TWD', 'AS', 'Asia'),
(222, 'TJ', 'TJK', 'Tajikistan', 'Dushanbe', 992, 'SM', 'TJS', 'AS', 'Asia'),
(223, 'TZ', 'TZA', 'Tanzania, United Republic of', 'Dodoma', 255, 'TSh', 'TZS', 'AF', 'Africa'),
(224, 'TH', 'THA', 'Thailand', 'Bangkok', 66, '฿', 'THB', 'AS', 'Asia'),
(225, 'TL', 'TLS', 'Timor-Leste', 'Dili', 670, '$', 'USD', 'AS', 'Asia'),
(226, 'TG', 'TGO', 'Togo', 'Lome', 228, 'CFA', 'XOF', 'AF', 'Africa'),
(227, 'TK', 'TKL', 'Tokelau', '', 690, '$', 'NZD', 'OC', 'Oceania'),
(228, 'TO', 'TON', 'Tonga', 'Nuku\'alofa', 676, '$', 'TOP', 'OC', 'Oceania'),
(229, 'TT', 'TTO', 'Trinidad and Tobago', 'Port of Spain', 1868, '$', 'TTD', 'NA', 'North America'),
(230, 'TN', 'TUN', 'Tunisia', 'Tunis', 216, 'ت.د', 'TND', 'AF', 'Africa'),
(231, 'TR', 'TUR', 'Turkey', 'Ankara', 90, '₺', 'TRY', 'AS', 'Asia'),
(232, 'TM', 'TKM', 'Turkmenistan', 'Ashgabat', 7370, 'T', 'TMT', 'AS', 'Asia'),
(233, 'TC', 'TCA', 'Turks and Caicos Islands', 'Cockburn Town', 1649, '$', 'USD', 'NA', 'North America'),
(234, 'TV', 'TUV', 'Tuvalu', 'Funafuti', 688, '$', 'AUD', 'OC', 'Oceania'),
(235, 'UG', 'UGA', 'Uganda', 'Kampala', 256, 'USh', 'UGX', 'AF', 'Africa'),
(236, 'UA', 'UKR', 'Ukraine', 'Kiev', 380, '₴', 'UAH', 'EU', 'Europe'),
(237, 'AE', 'ARE', 'United Arab Emirates', 'Abu Dhabi', 971, 'إ.د', 'AED', 'AS', 'Asia'),
(238, 'GB', 'GBR', 'United Kingdom', 'London', 44, '£', 'GBP', 'EU', 'Europe'),
(239, 'US', 'USA', 'United States', 'Washington', 1, '$', 'USD', 'NA', 'North America'),
(240, 'UM', 'UMI', 'United States Minor Outlying Islands', '', 1, '$', 'USD', 'NA', 'North America'),
(241, 'UY', 'URY', 'Uruguay', 'Montevideo', 598, '$', 'UYU', 'SA', 'South America'),
(242, 'UZ', 'UZB', 'Uzbekistan', 'Tashkent', 998, 'лв', 'UZS', 'AS', 'Asia'),
(243, 'VU', 'VUT', 'Vanuatu', 'Port Vila', 678, 'VT', 'VUV', 'OC', 'Oceania'),
(244, 'VE', 'VEN', 'Venezuela', 'Caracas', 58, 'Bs', 'VEF', 'SA', 'South America'),
(245, 'VN', 'VNM', 'Viet Nam', 'Hanoi', 84, '₫', 'VND', 'AS', 'Asia'),
(246, 'VG', 'VGB', 'Virgin Islands, British', 'Road Town', 1284, '$', 'USD', 'NA', 'North America'),
(247, 'VI', 'VIR', 'Virgin Islands, U.s.', 'Charlotte Amalie', 1340, '$', 'USD', 'NA', 'North America'),
(248, 'WF', 'WLF', 'Wallis and Futuna', 'Mata Utu', 681, '₣', 'XPF', 'OC', 'Oceania'),
(249, 'EH', 'ESH', 'Western Sahara', 'El-Aaiun', 212, 'MAD', 'MAD', 'AF', 'Africa'),
(250, 'YE', 'YEM', 'Yemen', 'Sanaa', 967, '﷼', 'YER', 'AS', 'Asia'),
(251, 'ZM', 'ZMB', 'Zambia', 'Lusaka', 260, 'ZK', 'ZMW', 'AF', 'Africa'),
(252, 'ZW', 'ZWE', 'Zimbabwe', 'Harare', 263, '$', 'ZWL', 'AF', 'Africa');